## Tensors

Tensors are similar to NumPy ndarrays, with the addition being that Tensors can also be used on a GPU to accelerate computing.

In [1]:
import torch
import numpy as np

Construct a 5x3 matrix, uninitialized:

In [2]:
x = torch.Tensor(5,3)
x


 0.0000e+00  2.0000e+00 -6.5505e+11
 1.0845e-19  5.6052e-45  0.0000e+00
 0.0000e+00  0.0000e+00  1.2885e+32
 4.9326e-43  4.1009e-09  4.5914e-41
 8.9683e-44  2.6331e+20  0.0000e+00
[torch.FloatTensor of size 5x3]

Construct a randomly initialized matrix

In [3]:
x = torch.rand(5,3)
x


 0.4705  0.1406  0.8318
 0.4040  0.1292  0.3685
 0.6752  0.2478  0.1011
 0.1925  0.8066  0.9070
 0.4168  0.4108  0.5288
[torch.FloatTensor of size 5x3]

Get its size

In [4]:
x.size()

torch.Size([5, 3])

* Note: torch.Size is in fact a tuple, so it supports the same operations

## Operations

In [5]:
y = torch.rand(5,3)
x + y


 1.3135  0.7746  1.7219
 0.7025  0.1372  0.5644
 1.1724  0.4825  0.8630
 0.6898  1.6982  1.0051
 1.0233  0.4390  0.9666
[torch.FloatTensor of size 5x3]

In [6]:
torch.add(x,y)


 1.3135  0.7746  1.7219
 0.7025  0.1372  0.5644
 1.1724  0.4825  0.8630
 0.6898  1.6982  1.0051
 1.0233  0.4390  0.9666
[torch.FloatTensor of size 5x3]

In [7]:
result = torch.Tensor(5, 3)
torch.add(x, y, out=result)
result


 1.3135  0.7746  1.7219
 0.7025  0.1372  0.5644
 1.1724  0.4825  0.8630
 0.6898  1.6982  1.0051
 1.0233  0.4390  0.9666
[torch.FloatTensor of size 5x3]

Addition in-place:

In [8]:
y.add_(x)
print(y)


 1.3135  0.7746  1.7219
 0.7025  0.1372  0.5644
 1.1724  0.4825  0.8630
 0.6898  1.6982  1.0051
 1.0233  0.4390  0.9666
[torch.FloatTensor of size 5x3]



You can use standard numpy-like indexing with all bells and whistles!

In [9]:
print(x[:, 1])


 0.1406
 0.1292
 0.2478
 0.8066
 0.4108
[torch.FloatTensor of size 5]



* Read later: 100+ Tensor operations, including transposing, indexing, slicing, mathematical operations, linear algebra, random numbers, etc are described here <http://pytorch.org/docs/torch>

## Numpy Bridge

- Converting a torch Tensor to a numpy array and vice versa is a breeze.
- The torch Tensor and numpy array will share their underlying memory locations, and changing one will change the other.

Convertng torch Tensor to numpy Array

In [10]:
a = torch.ones(5)
a


 1
 1
 1
 1
 1
[torch.FloatTensor of size 5]

In [11]:
b = a.numpy()
b

array([ 1.,  1.,  1.,  1.,  1.], dtype=float32)

See how the numpy array changed in value.

In [12]:
a.add_(1)


 2
 2
 2
 2
 2
[torch.FloatTensor of size 5]

In [13]:
a


 2
 2
 2
 2
 2
[torch.FloatTensor of size 5]

In [14]:
b

array([ 2.,  2.,  2.,  2.,  2.], dtype=float32)

Covering numpy Array to torch Tensor

See how changing the np array changedthe torch Tensor atomatically

In [15]:
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)

array([ 2.,  2.,  2.,  2.,  2.])

In [16]:
a

array([ 2.,  2.,  2.,  2.,  2.])

In [17]:
b


 2
 2
 2
 2
 2
[torch.DoubleTensor of size 5]

All the  Tensors on the CPU except a CharTensor support convering to Numpy and back.

## CUDA Tensors

Tensors can be moved onto GPU using the .cude function.

In [18]:
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    x + y
    print(x + y)

* References: http://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#tensors